### ISSUE TITLE
建議把臺語注音符號一起納入

### ISSUE THREAD

**Issue by marklh9** [bobbytung/Bopomofo_on_Web#1]
不曉得可不可以在這裡反應字型設計的建議。
由於臺語注音符號有些國語所沒有的調號，也同樣有調號標註位置的問題，希望也可以一起設計進來，方便使用。

測試結果請參考：

![tai1](https://user-images.githubusercontent.com/17537417/38400477-bf3c41ae-3982-11e8-8358-cacce3be1db7.png)
![tai2](https://user-images.githubusercontent.com/17537417/38400478-bf6198be-3982-11e8-8764-78773880e64d.png)

[bopomo.zip](https://github.com/bobbytung/BopomofoLayoutTest/files/1882448/bopomo.zip)

**Comment by bobbytung** [comment]
在最近一版的測試頁面中已經更新加入Bopomofo Extension的新字體，請到
https://bobbytung.github.io/Bopomofo_on_Web/case07/index.html
測試。
