### ISSUE TITLE
README.md 裡的一些敘述錯誤及建議

### ISSUE THREAD

**Issue by Yuijzeon** [bobbytung/Bopomofo_on_Web#11]
小弟我閒暇時間從事注音符號的研究
今天看到這個計劃我覺得非常的棒
但在 README.md 裡發現了一些錯誤
我這裡分成錯誤跟建議依照 README.md 裡的順序寫下去

【建議】_一般注音符號 | General Bopomofo Symbol_ 改為 _國語注音符號 | Mandarin Phonetic Symbols (MPS)_ 或 _基本注音符號 | Basic Bopomofo Letters_

雖然「一般注音符號」這個詞彙也能讓人了解，不過 Mandarin Phonetic Symbols 在翻譯上已經用了很長一段時間，所以我認為用「國語注音符號」較恰當。而第二種建議用 "Basic" 這個詞則是和 "extended" 相對。

【錯誤】調號 | Tone Mark 少了一個 ˉ(U+02C9)

【錯誤】_罕用注音符號 Rare Use Bopomofo Symbol_ 應改為 _老國音字母 Old Bopomofo Letters_ 或 _老國語注音符號 Old Mandarin Phonetic Symbols_ 並將 ㄫ(U+312B) 從方音注音符號移動至此

原先ㄪ(U+312A)、ㄬ(U+312C)、ㄭ(U+312D)三個注音和ㄫ(U+312B)被拆分開來，ㄫ(U+312B)被放入方音注音符號裡，但方音符號其實是有包含ㄪ(U+312A)、ㄬ(U+312C)以及所有的基本注音符號的，一般來說還是會把它們4個歸在老國音字母裡面。老國音字母是歷史上它們真正的名字 (對應國音字母，後來改稱國語注音符號)。其實 UNICODE 還有收入另外兩個符號ㄮ(U+312E 注音ㄜ的舊式寫法)和ㄯ(U+312F 不含韻腹ㄜ的韻尾ㄣ)在裡面。

【建議】_注音符號延伸 | Bopomofo Extended for Dialect_ 改為 _注音符號延伸 | Bopomofo Letters Extended_ 或 _注音符號延伸 | Bopomofo Symbols Extended_ 

Bopomofo Extended for Dialect 的意思應該是「方言用注音符號延伸」語意怪怪的，方言用和延伸留一即可。

【建議】_方音注音符號 | Bopomofo Symbol for Dialect_ 改為 _台語注音符號 | Taiwanese Phonetic Symbols (TPS)_ 並新增苗語注音符號的欄位

在 UNICODE 的 Bopomofo Extended 中除了台灣的方音符號還另外收錄了三個苗語注音符號(ㆹ、ㆸ、ㆺ)，因此我覺得 Bopomofo Symbol for Dialect 這個詞不夠精確。

【錯誤】ㆴ、ㆵ、ㆶ、ㆷ一般歸類在韻母，而非調號。

方音用的調號又分為方音符號用的和苗語注音用的，台語注音額外用了˪(U+02EA)、˫(U+02EB)。苗語注音(老國音字母中也是用到這4個)中額外用到　〪(U+302A)、　〫(U+302B)、　〬(U+302C)、　〭(U+302D)。

另外我吐槽一下，是哪個家伙跑去跟 UNICODE 提案增加小書ㄍ的 (我在這裡第一次聽說這檔事) ，應該要提案的是要把ㆶ(U+31B6)的字形從小書ㄎ改為小書ㄍ吧，這個字形本來就是 UNICODE 收錯，大家也用了一段時間了，增加小書ㄍ只會造成一個符號兩個 UNICODE 編碼。

**Comment by Yuijzeon** [comment]
【錯誤】少了一個方音符號ㆨ(U+31A8)

**Comment by YuRen-tw** [comment]
@Yuijzeon 
> 但方音符號其實是有包含ㄪ(U+312A)、ㄬ(U+312C)以及所有的基本注音符號的

可以參考教育部公布的「[方音符號系統](https://depart.moe.edu.tw/ed2400/News_Content.aspx?n=115F1082F1FB6842&sms=EFB4F5BEE71F2ECF&s=7999ED5540060D14)」
裡面聲母音標的部分並沒有包含「ㄪ」與「ㄬ」


> 是哪個家伙跑去跟 UNICODE 提案增加小書ㄍ的

詳細請見提案文件（ https://unicode.org/wg2/docs/n4980_Proposal-Bopomofo_Extended.pdf ）。


而在 [WG2 會議記錄(?)](http://www.unicode.org/L2/L2018/18217-wg2-consent-docket.pdf) 的 F 節可以看到是已知「ㆶ (U+31B6)」收錯的情形下決定的：
> ***F. Bopomofo***
> In N[4980](https://unicode.org/wg2/docs/n4980_Proposal-Bopomofo_Extended.pdf), TCA proposed one letter, U+31BB BOPOMOFO FINAL LETTER G, be added to Bopomofo Extended block. (The character U+31B6 BOPOMOFO FINAL LETTER K was a mistake and should have been the proposed character.) WG2 recommended the addition of U+31BB. The addition seems uncontroversial. 
>
> Recommendation: Accept the Bopomofo character.

**Comment by Yuijzeon** [comment]
@YuRen-tw 那份文件只有方音符號裡的台語注音符號，教育部出版的客家話教材就有包含ㄪ，1998年教育部公告的方音符號是吳守禮教授修訂 (http://olddoc.tmu.edu.tw/chiaushin/marker.pdf) 的，原本就包含了「ㄪ」、「ㄬ」與「ㆨ」(為了描述特殊地方腔調)。

ㆴ、ㆵ、ㆶ、ㆷ在**排序時**放在所有韻母之後的，前面我表達得不夠精確，不會和調號放在一起。

**Comment by Yuijzeon** [comment]
@ButTaiwan 我也覺得 UNICODE 會同意，畢竟 UNICDOE 現在收的字越來越雜了。不過在收了小書ㄍ之後入聲韻尾 /t/ 就會有兩個符號，現在大多數的做法 (例如萌典或其他地方用到方音符號的字型) 是將U+31B6的字圖直接做小書ㄍ。到時侯又會有一波新舊不相容的情形發生。

小書ㄍ和小書ㄎ既然分家了，那是不是要多收小書ㄆ和小書ㄊ了？ XDDD
(舊式的入聲韻尾寫法的確是用ㄆ、ㄊ和ㄎ。)

**Comment by ButTaiwan** [comment]
@Yuijzeon 實際上就是詢問過多位主持人意見，大家都**不認同**可以直接修改U+31B6囉。

**Comment by Yuijzeon** [comment]
@ButTaiwan 好吧，那就相信專業。雖然我不覺得他們平常有在用方音符號。

**Comment by ButTaiwan** [comment]
@Yuijzeon 因為改Unicode不是單純改Unicode這麼簡單。拿方音符號來說，他已經存在於Unicode裡快20年了，這20年之間，不知道有多少其他各國規格（已知的就有CNS11643與GB18030）也照收了這些符號。不知道有多少字型已經支援這些符號（因為GB18030是強制基準，意外地有很大量簡體字型有支援）。
忽然作整個字符字形完全改掉的修改，引起的不相容問題是很難預期的，所以一般都不太會同意這樣改。無論實際上它是常用還是少用。

**Comment by Yuijzeon** [comment]
@ButTaiwan 我是覺得直接改並無不妥，因為如果多加一個小書ㄍ，為了讓新舊網站、文件都能顯示正確的話，就必須將 U+31B6 和 U+31BB 兩個編碼的字形都做成小書ㄍ，新加的 U+31BB 還需要一段時間才能普及到大多數電子設備，在這一段時間我想我還是會用ㆶ(U+31B6) 來代表入聲韻尾 /t/ 吧...... 畢竟都提案了，等過幾年在全部改 U+31BB 想到就累......

其他各國規格我是不瞭解啦，不過我知道注音符號只有台灣在用。你們對於方音符號ㆦ(U+31A6)類的注音都提出字形修正，我還是不太明白為何ㆶ不能比照辦理，我認為新增小書ㄍ造成不相容的影響程度遠大於修改小書ㄎ的迎響程度。

還是感謝各位對於注音符號在電腦顯示上所做的貢獻。

**Comment by ButTaiwan** [comment]
@Yuijzeon 例如，GB18030不跟著改怎麼辦？是否造成Unicode與GB18030未來的矛盾？
就像蘇州碼在Unicode裡的名稱一直都是  Hangzhou style numerals，Unicode 承認名稱錯誤，但不能改，因為很難去維持既有資料的相容性。
錯誤的字，既然已經被標準化過，也只好承認這是錯誤，就讓它留下來。這是文字編碼基本的態度。
例如常見的幽靈漢字。
https://zh.wikipedia.org/wiki/%E5%B9%BD%E9%9D%88%E6%BC%A2%E5%AD%97
網路上不知道有多少文章在討論幽靈漢字。如果直接在新版去把「妛」訂正成正確的「𡚴」，那既有的文章都會變成不知所云。
U+31B6也是一樣，誰知道會不會有人就是拿他來當作小ㄎ用。（直覺是應該很少，但是無從舉證。但無從舉證就很難跟來自世界各國的與會專家們去保證這樣修改沒問題，到處都會有異見。）

至於為什麼U+31A6等符號可以直接改呢，這個也很趣味。從上面的提案文件可以看到，我們有去找到從20年前的第一份提案文件起，與Unicode發佈後歷年各版本的造型。
從證據可顯示，U+31A6當初提案時形狀是正確的，極早期的Unicdoe標準提供的範例字形也是正確的，是後來隨著版本更新字形才愈來愈走樣的。所以這些字只是**恢復當年accepted時的樣子**，因為當初加入的字本來就是對的，並**沒有**牽涉改字的問題。

但U+31B6是個謎，從第一份提案文件開始就寫成ㄎ了。上面這套論據完全沒辦法自圓其說。

ps. 我一直想說，它是 /k/ 啦...

**Comment by Yuijzeon** [comment]
@ButTaiwan 我了解，不過既然小書ㄍ和小書ㄎ分家了，下一版提案能不能將小書ㄆ和小書ㄊ一起加入，這樣小書ㄎ就能當作小書ㄍ的歷史形式了。

另外，ㄍ的音標是 /k/ 沒錯，ㄎ的音標是 /kʰ/ 。音標是用輕濁分 /g/, /k/ ，而注音是用送不送氣分ㄍ、ㄎ (再講下去就扯到音韻學去了)

另外我還建議將 注音符號DU (帶圓圈的ㄉ)、 注音符號OE (方音符號的字型為角狀的ㄜ，舊式閏音符號寫法為ㄚ中間加一橫) 加入編碼裡，畢竟這兩個符號的出現頻率比ㄮ(U+312E)高多了，在敘述方音符號歷史時會用到，現今仍有地方腔調需要這些符號。

另外我覺得要收錄的是 福州話注音OE (http://www.study.matsu.edu.tw/1000/index.html) 以音位來說這個和上面的注音符號OE擇一收錄即可，重複收錄也行 (如同 UNICODE 收了兩個形式的ㄜ一樣)

上面是現在仍會用到的

下面的符號則是歷史形式的注音符號 (可收可不收)

所有的閏音符號 (https://github.com/dqwyy/Zhuyinfuhao-Zongbiao)
南島語注音符號 (不過這部分我不熟，還需要另外蒐集資料)

**Comment by Yuijzeon** [comment]
@ButTaiwan 我了解，不過既然小書ㄍ和小書ㄎ分家了，下一版提案能不能將小書ㄆ和小書ㄊ一起加入，這樣小書ㄎ就能當作小書ㄍ的歷史形式了。

另外，ㄍ的音標是 /k/ 沒錯，ㄎ的音標是 /kʰ/ 。音標是用輕濁分 /g/, /k/ ，而注音是用送不送氣分ㄍ、ㄎ (再講下去就扯到音韻學去了)

另外我還建議將 注音符號DU (帶圓圈的ㄉ)、 注音符號OE (方音符號的字型為角狀的ㄜ，舊式閏音符號寫法為ㄚ中間加一橫) 加入編碼裡，畢竟這兩個符號的出現頻率比ㄮ(U+312E)高多了，在敘述方音符號歷史時會用到，現今仍有地方腔調需要這些符號。

另外我覺得要收錄的是 福州話注音OE (http://www.study.matsu.edu.tw/1000/index.html) 以音位來說這個和上面的注音符號OE擇一收錄即可，重複收錄也行 (如同 UNICODE 收了兩個形式的ㄜ一樣)

上面是現在仍會用到的

下面的符號則是歷史形式的注音符號 (可收可不收)

所有的閏音符號 (https://github.com/dqwyy/Zhuyinfuhao-Zongbiao)
南島語注音符號 (不過這部分我不熟，還需要另外蒐集資料)

**Comment by ButTaiwan** [comment]
@Yuijzeon 簡單的說呢，要收這些符號，要先變出官方文件。目前我們找到比較有效的官方文件只有教育部那方音符號方案。
20世紀末Unicode剛組成，審查太鬆了，才會發生小ㄎ完全沒附佐證就直接通過的問題。
無論要補充歷史小ㄊ，還是閏音符號等，先找出足夠官方文件，會比較好提。

說實話我覺得，要提案加入台灣語假名說不定還比較簡單，體系化的文件是完整的....。

**Comment by Yuijzeon** [comment]
@ButTaiwan 教會文件行嗎？我沒申請過 UNICODE 的碼位，不過苗語注音我記得在申請的時候只拿了幾個聖經的頁面而已，如果可以的話南島語注音符號就也能收了

**Comment by Yuijzeon** [comment]
@ButTaiwan 我覺得當初在收小書ㄎ時應該純粹只是收錯而已

還有明明我列了很多點怎麼只討論小書ㄎ啊 QwQ

**Comment by ButTaiwan** [comment]
@Yuijzeon 
國語會那份最後不是只成為草案，沒有完全實施嗎？ 有人有興趣試試看的話，我會給予祝福的:P
這次是因為跟 @bobbytung 合作要讓注音字型的排版正常化，順便解決 Unicode 裡**既有**字符的問題，才去提這個新增小ㄍ與方音符號字型修正案的。至於要新增的話，我對這些方言也不懂，還是交給專業研究者去主導比較好。

乍看的感覺是字數有點多，目前的 Bopomofo Exteneded 區會擺不下，還要爭取一塊新位置，應該會是個大工程。
而且福州化注音看起來還需要新的聲調符號？

**Comment by Yuijzeon** [comment]
@ButTaiwan 閏音符號可收可不收 (我上面有寫) 因為現在基本上用不到

閏音符號後來有實施的，中共人民政府初期也有用閏音符號 (但有稍作修改) 不過後來普及的是漢語拼音

比較需要收的 (現今仍然使用的) 是 注音符號DU 、 注音符號OE ，以及福州話注音

福州話注音要新的聲調符號沒錯

但我不會福州話 (我只是有粗略的研究過) 真正要討論的話還是找福州話注音的設計團隊吧

**Comment by Yuijzeon** [comment]
@ButTaiwan 有您的聯絡方式嗎？可以的話我想問關於 UNICODE 編碼提案的相關事項，可以的話我希望能夠將閏音符號和台灣語假名收錄進 UNICODE 。

**Comment by Yuijzeon** [comment]
@bobbytung 其實我對 UNICODE 的收錄標準一直搞不清楚，如果ㄮ(U+312E)和ㄯ(U+312F)能收，理論上閏音符號應該都能收

**Comment by Yuijzeon** [comment]
@bobbytung 感謝您提供的傳送門，有空我會研究的 ^w^

**Comment by bobbytung** [comment]
@Yuijzeon 那兩個符號好像是某位老外在文獻上看到而提出去，結果過了的提案。
但他只是看到有這符號，沒有提到後面的體系以及用法。如果有具體的文獻，我想都會收錄。

**Comment by Yuijzeon** [comment]
@bobbytung ......我只能說 UNICODE的收錄標準真的很奇葩

剛剛看了連結，加入會員要750美金啊 Orz

我還是別想這些好了

**Comment by bobbytung** [comment]
@Yuijzeon 提出字碼提案不限會員。

**Comment by Yuijzeon** [comment]
@bobbytung 小勘誤

英文的 Symbol, Symbols 建議全部統一為 Symbols

ㄪ在客語方音符號中也是常用符號喔 在教育部終身司的 [客家語拼音方案](https://depart.moe.edu.tw/ed2400/News_Content.aspx?n=5EB26D97D6A29617&sms=8C59E176B3E3F56E&s=30783F04D0989E57) 裡有寫到

Tone Mark Symbol for Dialect 可改為 Tone Marks for Dialect

**Comment by Yuijzeon** [comment]
再次感謝 @bobbytung 提供的相關資訊，希望能早日讓注音的 Ruby 無痛在數位裝置上顯示。

**Comment by Yuijzeon** [comment]
@ButTaiwan 可以再請教您一個問題嗎？在前幾年我就有想過用 GPOS 來做注音標音，但我不太會調相關參數 (我用的軟體是 FontForge) ，最後是改用 "calt" 加 "aalt" 只能實現橫書時注音在右邊的字型，無法如同您做出的字型橫書時標住在上方、直書時標記在左方，能否寫個教學之類的文章，謝謝

**Comment by ButTaiwan** [comment]
字型的 feature 檔案有公開在 font 目錄啊。

**Comment by Yuijzeon** [comment]
@ButTaiwan 了解，我拿檔案去研究研究，謝謝

**Comment by Yuijzeon** [comment]
@bobbytung 我去 UNICODE 的提案頁面搜尋，[ㄮ(U+312E)](http://www.unicode.org/wg2/docs/n4695-Discussion%20of%202CEF1.pdf)和[ㄯ(U+312F)](https://unicode.org/L2/L2016/16106-n4717-bopomofo.pdf)應該不是老外收的，是一個名字叫 Andrew West 的人提案的，有趣的是在ㄮ(U+312E)的提案者中，還有一位 Liang Hai ，不知道這位 Liang Hai 和本篇 Stargazers 裡的 [Liang Hai](https://github.com/lianghai) 是不是同一個人。

**Comment by bobbytung** [comment]
@Yuijzeon [Andrew West](https://en.wikipedia.org/wiki/Andrew_West_(linguist))是老外啊😂。
另外你要找梁海嗎？

**Comment by Yuijzeon** [comment]
@bobbytung 我看到梁海是中國人我還以為 Andrew West (Wèi Ān) 也是中國人，原來誤會大了阿 @@

是的，可以的話我想找梁海問他當初提案的細節

**Comment by lianghai** [comment]
（Ken Lunde 刚才特地发了邮件给 Andrew 和我提醒说我们的名字在这个 issue 里有提及。）

@Yuijzeon 

我并没有怎么参与 WG2 N4695。当时只是和 Andrew 交换了一些意见并帮他找到了《國語月刊·漢字改革號》中的几处参考。我个人并不支持该字符的编码。

Andrew West（中文名「魏安」）是英国人。Andrew 懂汉语，但具体取决于你的英语能力，你们英语交流可能会更轻松一些。

对 BOPOMOFO FINAL LETTER G 这个提案如果还有意见，理解清楚这里各位给你解释的理由之后，给 UTC 提交文档清楚分析你的主张。

> 小書ㄆ、小書ㄊ、小書ㄎ是一組 (作為歷史形式) ，如果他真的要表示小書ㄎ的話，那他還必須要小書ㄆ、小書ㄊ才完整。

承认原有字符的错误不代表承认原有字符的编码必要性，更不代表主张编码整个系统。不要过度解读编码决议。

> 剛剛看了連結，加入會員要750美金啊 Orz

Unicode 联盟根本就没有750美元的一档成员身份。

**Comment by kenlunde** [comment]
> Unicode 联盟根本就没有750美元的一档成员身份。

That's the price for an individual **life** [membership](https://www.unicode.org/consortium/joinform.html). An individual membership is $75 per year if paid annually. I am likely to be involved with Unicode until I die, so the life membership option made a lot of sense. I am sure that Andrew had the same reasoning.

**Comment by Yuijzeon** [comment]
@lianghai @kenlunde 我剛剛查了一下之前我應該是看錯了， $750 好像是終身的，一年是 $75 

@lianghai 了解，我現在比較想做的是將 DU 和 OE 加入編碼，這對於方言的標註有相當大的重要性
